# Generated by Django 5.1.6 on 2025-03-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_colors_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
