# Generated by Django 5.1.6 on 2025-05-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name_plural': 'Product Gallery'},
        ),
    ]
